import { avlDelete, avlInsert, avlLL, avlLR, avlRL, avlRR } from "./avl";
import { binomialHeap, fibonacciHeap } from "./advanced-heaps";
import {
  btDepth,
  btHeight,
  btInorder,
  btLevelorder,
  btPostorder,
  btPreorder,
  btSearch,
} from "./binary";
import {
  bstDelete,
  bstInsert,
  bstMinMax,
  bstPredecessor,
  bstSearch,
  bstSuccessor,
} from "./bst";
import { bplus, btree, ttTree, ttfTree } from "./btree";
import { fenwick } from "./fenwick";
import {
  heapBuild,
  heapExtract,
  heapHeapify,
  heapMaxInsert,
  heapMinInsert,
  heapSort,
} from "./heap";
import { karyTree, naryTree } from "./nary";
import { radixTrie, ternarySearchTree } from "./radix-tst";
import { rbDelete, rbInsert } from "./rbtree";
import {
  segBuild,
  segPointUpdate,
  segRangeMax,
  segRangeMin,
  segRangeSum,
  segRangeUpdate,
} from "./segment";
import { TREE_CODE } from "./snippets";
import { cartesian, intervalTree, kdTree, suffixTree } from "./specialized";
import { trieDelete, trieInsert, triePrefix, trieSearch } from "./trie";
import type { TreeAlgoId, TreeInput, TreeMeta, TreeRunner } from "./types";

export type { TreeAlgoId, TreeInput, TreeMeta, TreeFrame, TreeKind } from "./types";
export { generateTreeInput, shuffleSeed } from "./random";

function meta(partial: Omit<TreeMeta, "code"> & { id: TreeAlgoId }): TreeMeta {
  return { ...partial, code: TREE_CODE[partial.id] };
}

export const TREE_META: TreeMeta[] = [
  meta({
    id: "bt-preorder",
    name: "Preorder",
    group: "Binary Tree",
    kind: "binary",
    worst: "O(n)",
    average: "O(n)",
    best: "O(n)",
    space: "O(h)",
    available: true,
    definition: "Visit the root, then recursively traverse the left and right subtrees.",
    usage: "Copying trees, prefix expression export, and hierarchical serialization.",
  }),
  meta({
    id: "bt-inorder",
    name: "Inorder",
    group: "Binary Tree",
    kind: "binary",
    worst: "O(n)",
    average: "O(n)",
    best: "O(n)",
    space: "O(h)",
    available: true,
    definition: "Traverse left, visit root, traverse right — sorted order on a BST.",
    usage: "Printing BST keys in order and validating binary-search structure.",
  }),
  meta({
    id: "bt-postorder",
    name: "Postorder",
    group: "Binary Tree",
    kind: "binary",
    worst: "O(n)",
    average: "O(n)",
    best: "O(n)",
    space: "O(h)",
    available: true,
    definition: "Traverse both children before visiting the node itself.",
    usage: "Deleting trees safely and evaluating postfix expression trees.",
  }),
  meta({
    id: "bt-levelorder",
    name: "Level-order",
    group: "Binary Tree",
    kind: "binary",
    worst: "O(n)",
    average: "O(n)",
    best: "O(n)",
    space: "O(w)",
    available: true,
    definition: "BFS across depths — each level left to right.",
    usage: "Serialization by levels and shortest root-to-node hop counts.",
  }),
  meta({
    id: "bt-height",
    name: "Height",
    group: "Binary Tree",
    kind: "binary",
    worst: "O(n)",
    average: "O(n)",
    best: "O(n)",
    space: "O(h)",
    available: true,
    definition: "Height is one plus the longer child height (empty tree is 0).",
    usage: "Balance checks and analyzing tree shape.",
  }),
  meta({
    id: "bt-depth",
    name: "Depth",
    group: "Binary Tree",
    kind: "binary",
    worst: "O(h)",
    average: "O(h)",
    best: "O(1)",
    space: "O(1)",
    available: true,
    definition: "Depth counts edges on the path from the root down to a node.",
    usage: "Level indexing and distance-from-root queries.",
  }),
  meta({
    id: "bt-search",
    name: "Search",
    group: "Binary Tree",
    kind: "binary",
    worst: "O(n)",
    average: "O(h)",
    best: "O(1)",
    space: "O(1)",
    available: true,
    definition:
      "Walk left/right comparing keys until the target is found or the path ends.",
    usage: "Membership tests on ordered binary trees.",
  }),

  meta({
    id: "bst-insert",
    name: "Insert",
    group: "BST",
    kind: "bst",
    worst: "O(n)",
    average: "O(log n)",
    best: "O(log n)",
    space: "O(1)",
    available: true,
    definition: "Walk from the root to a null child link and attach the new key.",
    usage: "Dynamic ordered sets without balancing.",
  }),
  meta({
    id: "bst-search",
    name: "Search",
    group: "BST",
    kind: "bst",
    worst: "O(n)",
    average: "O(log n)",
    best: "O(1)",
    space: "O(1)",
    available: true,
    definition: "Compare with the current key and branch left or right.",
    usage: "Dictionary lookup and ordered membership.",
  }),
  meta({
    id: "bst-delete",
    name: "Delete",
    group: "BST",
    kind: "bst",
    worst: "O(n)",
    average: "O(log n)",
    best: "O(log n)",
    space: "O(1)",
    available: true,
    definition: "Handle leaf, one-child, and two-child (successor) cases.",
    usage: "Removing keys while preserving BST order.",
  }),
  meta({
    id: "bst-minmax",
    name: "Min / Max",
    group: "BST",
    kind: "bst",
    worst: "O(n)",
    average: "O(log n)",
    best: "O(log n)",
    space: "O(1)",
    available: true,
    definition: "The minimum is the leftmost node; the maximum is the rightmost.",
    usage: "Range endpoints and successor/predecessor helpers.",
  }),
  meta({
    id: "bst-predecessor",
    name: "Predecessor",
    group: "BST",
    kind: "bst",
    worst: "O(n)",
    average: "O(log n)",
    best: "O(1)",
    space: "O(1)",
    available: true,
    definition: "Largest key smaller than a node — max of left subtree or an ancestor.",
    usage: "Ordered iteration and floor queries.",
  }),
  meta({
    id: "bst-successor",
    name: "Successor",
    group: "BST",
    kind: "bst",
    worst: "O(n)",
    average: "O(log n)",
    best: "O(1)",
    space: "O(1)",
    available: true,
    definition: "Smallest key larger than a node — min of right subtree or an ancestor.",
    usage: "Inorder stepping and ceiling queries.",
  }),

  meta({
    id: "avl-insert",
    name: "Insert",
    group: "AVL",
    kind: "avl",
    worst: "O(log n)",
    average: "O(log n)",
    best: "O(log n)",
    space: "O(1)",
    available: true,
    definition: "BST insert, then rebalance with LL/RR/LR/RL rotations so |bf| ≤ 1.",
    usage: "Guaranteed logarithmic dictionaries with strict height balance.",
  }),
  meta({
    id: "avl-delete",
    name: "Delete",
    group: "AVL",
    kind: "avl",
    worst: "O(log n)",
    average: "O(log n)",
    best: "O(log n)",
    space: "O(1)",
    available: true,
    definition: "BST delete followed by upward rebalancing rotations.",
    usage: "Maintaining AVL shape after removals.",
  }),
  meta({
    id: "avl-ll",
    name: "LL Rotation",
    group: "AVL",
    kind: "avl",
    worst: "O(1)",
    average: "O(1)",
    best: "O(1)",
    space: "O(1)",
    available: true,
    definition: "Left-heavy chain fixed by a single right rotation.",
    usage: "Core AVL rebalance case after left-left growth.",
  }),
  meta({
    id: "avl-rr",
    name: "RR Rotation",
    group: "AVL",
    kind: "avl",
    worst: "O(1)",
    average: "O(1)",
    best: "O(1)",
    space: "O(1)",
    available: true,
    definition: "Right-heavy chain fixed by a single left rotation.",
    usage: "Core AVL rebalance case after right-right growth.",
  }),
  meta({
    id: "avl-lr",
    name: "LR Rotation",
    group: "AVL",
    kind: "avl",
    worst: "O(1)",
    average: "O(1)",
    best: "O(1)",
    space: "O(1)",
    available: true,
    definition:
      "Left child is right-heavy — left-rotate the child, then right-rotate the node.",
    usage: "Double rotation when insertion zig-zags.",
  }),
  meta({
    id: "avl-rl",
    name: "RL Rotation",
    group: "AVL",
    kind: "avl",
    worst: "O(1)",
    average: "O(1)",
    best: "O(1)",
    space: "O(1)",
    available: true,
    definition:
      "Right child is left-heavy — right-rotate the child, then left-rotate the node.",
    usage: "Double rotation mirror of LR.",
  }),

  meta({
    id: "rb-insert",
    name: "Insert",
    group: "Red-Black",
    kind: "rb",
    worst: "O(log n)",
    average: "O(log n)",
    best: "O(log n)",
    space: "O(1)",
    available: true,
    definition:
      "Insert a red node, then recolor and rotate until red-black invariants hold.",
    usage: "std::map / TreeMap-style balanced trees with cheaper rebalancing than AVL.",
  }),
  meta({
    id: "rb-delete",
    name: "Delete",
    group: "Red-Black",
    kind: "rb",
    worst: "O(log n)",
    average: "O(log n)",
    best: "O(log n)",
    space: "O(1)",
    available: true,
    definition: "Remove a node and restore black-height with recoloring and rotations.",
    usage: "Balanced deletion in red-black dictionaries.",
  }),

  meta({
    id: "heap-min-insert",
    name: "Min-Heap Insert",
    group: "Heap",
    kind: "minheap",
    worst: "O(log n)",
    average: "O(log n)",
    best: "O(1)",
    space: "O(1)",
    available: true,
    definition: "Append then sift up while the child is smaller than its parent.",
    usage: "Priority queues that always expose the minimum.",
  }),
  meta({
    id: "heap-max-insert",
    name: "Max-Heap Insert",
    group: "Heap",
    kind: "maxheap",
    worst: "O(log n)",
    average: "O(log n)",
    best: "O(1)",
    space: "O(1)",
    available: true,
    definition: "Append then sift up while the child is larger than its parent.",
    usage: "Priority queues that always expose the maximum.",
  }),
  meta({
    id: "heap-extract",
    name: "Extract Min/Max",
    group: "Heap",
    kind: "minheap",
    worst: "O(log n)",
    average: "O(log n)",
    best: "O(log n)",
    space: "O(1)",
    available: true,
    definition: "Swap root with last, shrink, then sift down to restore the heap.",
    usage: "Popping the next priority element.",
  }),
  meta({
    id: "heap-heapify",
    name: "Heapify",
    group: "Heap",
    kind: "minheap",
    worst: "O(log n)",
    average: "O(log n)",
    best: "O(1)",
    space: "O(1)",
    available: true,
    definition: "Sift down from a given index until the heap property holds below it.",
    usage: "Local repair inside build-heap and extract.",
  }),
  meta({
    id: "heap-build",
    name: "Build Heap",
    group: "Heap",
    kind: "minheap",
    worst: "O(n)",
    average: "O(n)",
    best: "O(n)",
    space: "O(1)",
    available: true,
    definition: "Heapify every non-leaf from the bottom up — linear time overall.",
    usage: "Turning an arbitrary array into a heap.",
  }),
  meta({
    id: "heap-sort",
    name: "Heap Sort",
    group: "Heap",
    kind: "maxheap",
    worst: "O(n log n)",
    average: "O(n log n)",
    best: "O(n log n)",
    space: "O(1)",
    available: true,
    definition: "Build a max-heap, then repeatedly swap the root into the sorted suffix.",
    usage: "In-place comparison sort with predictable bounds.",
  }),

  meta({
    id: "trie-insert",
    name: "Insert",
    group: "Trie",
    kind: "trie",
    worst: "O(L)",
    average: "O(L)",
    best: "O(L)",
    space: "O(L)",
    available: true,
    definition:
      "Follow character edges, creating nodes as needed, then mark the word end.",
    usage: "Dictionaries, autocomplete indexes, and IP routing tables.",
  }),
  meta({
    id: "trie-search",
    name: "Search",
    group: "Trie",
    kind: "trie",
    worst: "O(L)",
    average: "O(L)",
    best: "O(L)",
    space: "O(1)",
    available: true,
    definition:
      "Walk the word’s characters; succeed only if the final node is an end mark.",
    usage: "Exact word membership in a dictionary.",
  }),
  meta({
    id: "trie-delete",
    name: "Delete",
    group: "Trie",
    kind: "trie",
    worst: "O(L)",
    average: "O(L)",
    best: "O(L)",
    space: "O(L)",
    available: true,
    definition: "Clear the end mark and prune branches that no longer hold words.",
    usage: "Removing terms from a prefix tree.",
  }),
  meta({
    id: "trie-prefix",
    name: "Prefix / Autocomplete",
    group: "Trie",
    kind: "trie",
    worst: "O(L + k)",
    average: "O(L + k)",
    best: "O(L)",
    space: "O(k)",
    available: true,
    definition: "Walk the prefix, then DFS the subtree to list completed words.",
    usage: "Search suggestions and prefix filters.",
  }),

  meta({
    id: "seg-build",
    name: "Build",
    group: "Segment Tree",
    kind: "segment",
    worst: "O(n)",
    average: "O(n)",
    best: "O(n)",
    space: "O(n)",
    available: true,
    definition: "Leaves store the array; each parent combines its two children.",
    usage: "Preprocessing for fast range queries.",
  }),
  meta({
    id: "seg-range-sum",
    name: "Range Sum",
    group: "Segment Tree",
    kind: "segment",
    worst: "O(log n)",
    average: "O(log n)",
    best: "O(1)",
    space: "O(1)",
    available: true,
    definition: "Cover [L, R] with O(log n) disjoint segment nodes and sum them.",
    usage: "Range totals on a mutable array.",
  }),
  meta({
    id: "seg-range-min",
    name: "Range Minimum",
    group: "Segment Tree",
    kind: "segment",
    worst: "O(log n)",
    average: "O(log n)",
    best: "O(1)",
    space: "O(1)",
    available: true,
    definition: "Same canonical cover as range sum, combining with min.",
    usage: "RMQ when updates are also required.",
  }),
  meta({
    id: "seg-range-max",
    name: "Range Maximum",
    group: "Segment Tree",
    kind: "segment",
    worst: "O(log n)",
    average: "O(log n)",
    best: "O(1)",
    space: "O(1)",
    available: true,
    definition: "Canonical segment cover combined with max.",
    usage: "Range maximum queries with updates.",
  }),
  meta({
    id: "seg-point-update",
    name: "Point Update",
    group: "Segment Tree",
    kind: "segment",
    worst: "O(log n)",
    average: "O(log n)",
    best: "O(log n)",
    space: "O(1)",
    available: true,
    definition: "Change a leaf and recompute every ancestor up to the root.",
    usage: "Keeping range queries correct after single-cell edits.",
  }),
  meta({
    id: "seg-range-update",
    name: "Range Update",
    group: "Segment Tree",
    kind: "segment",
    worst: "O(n)",
    average: "O(n)",
    best: "O(log n)",
    space: "O(1)",
    available: true,
    definition:
      "Add a value across a range. This viz shows successive point updates; production code uses lazy propagation.",
    usage: "Bulk increments on intervals (lazy segment trees).",
  }),

  // Extended structures
  meta({
    id: "nary-tree",
    name: "N-ary Tree",
    group: "Basic Trees",
    kind: "binary",
    worst: "O(n)",
    average: "O(n)",
    best: "O(n)",
    space: "O(n)",
    available: true,
    definition:
      "Each node may have any number of children. Built here by attaching keys under existing parents, then traversed level-order.",
    usage: "File systems, DOM trees, and general hierarchical data.",
  }),
  meta({
    id: "kary-tree",
    name: "K-ary Tree",
    group: "Basic Trees",
    kind: "binary",
    worst: "O(n)",
    average: "O(n)",
    best: "O(n)",
    space: "O(n)",
    available: true,
    definition:
      "A complete tree where every node has at most k children (k=3 in this viz).",
    usage: "Game trees, heap-like layouts, and fixed-arity hierarchies.",
  }),
  meta({
    id: "tt-tree",
    name: "2-3 Tree",
    group: "Balanced Search",
    kind: "bst",
    worst: "O(log n)",
    average: "O(log n)",
    best: "O(log n)",
    space: "O(n)",
    available: true,
    definition:
      "Nodes hold 1–2 keys and 2–3 children; splits keep the tree perfectly balanced.",
    usage: "Predecessor of B-trees; guaranteed logarithmic height.",
  }),
  meta({
    id: "ttf-tree",
    name: "2-3-4 Tree",
    group: "Balanced Search",
    kind: "bst",
    worst: "O(log n)",
    average: "O(log n)",
    best: "O(log n)",
    space: "O(n)",
    available: true,
    definition:
      "Nodes hold 1–3 keys; isomorphic to red-black trees via 2/3/4-node mapping.",
    usage: "Teaching balanced multiway trees and RB equivalence.",
  }),
  meta({
    id: "btree",
    name: "B-Tree",
    group: "Balanced Search",
    kind: "bst",
    worst: "O(log n)",
    average: "O(log n)",
    best: "O(log n)",
    space: "O(n)",
    available: true,
    definition:
      "High-fanout balanced search tree with splits when nodes exceed max keys.",
    usage: "Database indexes and filesystems (large block-sized nodes).",
  }),
  meta({
    id: "bplus",
    name: "B+ Tree",
    group: "Balanced Search",
    kind: "bst",
    worst: "O(log n)",
    average: "O(log n)",
    best: "O(log n)",
    space: "O(n)",
    available: true,
    definition:
      "Like a B-tree, but all records live in leaves; internals store separators only.",
    usage: "SQL range scans and clustered indexes.",
  }),
  meta({
    id: "binomial-heap",
    name: "Binomial Heap",
    group: "Heap",
    kind: "minheap",
    worst: "O(log n)",
    average: "O(log n)",
    best: "O(1)",
    space: "O(n)",
    available: true,
    definition:
      "Forest of binomial trees; insert links equal-order trees like binary addition.",
    usage: "Mergeable priority queues.",
  }),
  meta({
    id: "fibonacci-heap",
    name: "Fibonacci Heap",
    group: "Heap",
    kind: "minheap",
    worst: "O(log n)",
    average: "O(1)*",
    best: "O(1)",
    space: "O(n)",
    available: true,
    definition:
      "Lazy root-list inserts; consolidate by degree on extract-min for amortized speed.",
    usage: "Dijkstra / Prim with decrease-key in theory textbooks.",
  }),
  meta({
    id: "radix-trie",
    name: "Radix / Compressed Trie",
    group: "Trie",
    kind: "trie",
    worst: "O(L)",
    average: "O(L)",
    best: "O(L)",
    space: "O(L)",
    available: true,
    definition: "Trie edges store substrings; splits compress shared prefixes.",
    usage: "Routing tables, dictionaries with long shared prefixes.",
  }),
  meta({
    id: "tst",
    name: "Ternary Search Tree",
    group: "Trie",
    kind: "trie",
    worst: "O(L + n)",
    average: "O(L + log n)",
    best: "O(L)",
    space: "O(n)",
    available: true,
    definition:
      "Each node holds one character with left/mid/right links like a BST of chars.",
    usage: "Space-efficient string sets and near-neighbor string search.",
  }),
  meta({
    id: "fenwick",
    name: "Fenwick Tree (BIT)",
    group: "Segment Tree",
    kind: "segment",
    worst: "O(log n)",
    average: "O(log n)",
    best: "O(log n)",
    space: "O(n)",
    available: true,
    definition: "Binary Indexed Tree — point updates and prefix sums via i ± i&−i.",
    usage: "Competitive programming frequency tables and prefix aggregates.",
  }),
  meta({
    id: "interval-tree",
    name: "Interval Tree",
    group: "Specialized",
    kind: "bst",
    worst: "O(n)",
    average: "O(log n + k)",
    best: "O(log n)",
    space: "O(n)",
    available: true,
    definition: "BST on interval lows with subtree max-high for stabbing queries.",
    usage: "Calendar conflicts, genome intervals, scheduling.",
  }),
  meta({
    id: "suffix-tree",
    name: "Suffix Tree",
    group: "Specialized",
    kind: "trie",
    worst: "O(n²)",
    average: "O(n²)",
    best: "O(n)",
    space: "O(n)",
    available: true,
    definition: "Compressed trie of all suffixes (naive build shown; Ukkonen is linear).",
    usage: "Substring search, longest repeated substring, bioinformatics.",
  }),
  meta({
    id: "cartesian",
    name: "Cartesian Tree",
    group: "Specialized",
    kind: "binary",
    worst: "O(n)",
    average: "O(n)",
    best: "O(n)",
    space: "O(n)",
    available: true,
    definition:
      "Binary tree that is a heap on values and a BST on positions — built with a stack in linear time.",
    usage: "RMQ reductions and treaps’ shape intuition.",
  }),
  meta({
    id: "kd-tree",
    name: "KD-Tree",
    group: "Specialized",
    kind: "binary",
    worst: "O(n)",
    average: "O(n log n)",
    best: "O(n log n)",
    space: "O(n)",
    available: true,
    definition:
      "Space-partitioning BST alternating split axes (x/y) for multidimensional points.",
    usage: "Nearest neighbor, range search in 2D/3D.",
  }),
];

export const TREE_RUNNERS: Partial<Record<TreeAlgoId, TreeRunner>> = {
  "bt-preorder": btPreorder,
  "bt-inorder": btInorder,
  "bt-postorder": btPostorder,
  "bt-levelorder": btLevelorder,
  "bt-height": btHeight,
  "bt-depth": btDepth,
  "bt-search": btSearch,
  "bst-insert": bstInsert,
  "bst-search": bstSearch,
  "bst-delete": bstDelete,
  "bst-minmax": bstMinMax,
  "bst-predecessor": bstPredecessor,
  "bst-successor": bstSuccessor,
  "avl-insert": avlInsert,
  "avl-delete": avlDelete,
  "avl-ll": avlLL,
  "avl-rr": avlRR,
  "avl-lr": avlLR,
  "avl-rl": avlRL,
  "rb-insert": rbInsert,
  "rb-delete": rbDelete,
  "heap-min-insert": heapMinInsert,
  "heap-max-insert": heapMaxInsert,
  "heap-extract": heapExtract,
  "heap-heapify": heapHeapify,
  "heap-build": heapBuild,
  "heap-sort": heapSort,
  "trie-insert": trieInsert,
  "trie-search": trieSearch,
  "trie-delete": trieDelete,
  "trie-prefix": triePrefix,
  "seg-build": segBuild,
  "seg-range-sum": segRangeSum,
  "seg-range-min": segRangeMin,
  "seg-range-max": segRangeMax,
  "seg-point-update": segPointUpdate,
  "seg-range-update": segRangeUpdate,
  "nary-tree": naryTree,
  "kary-tree": karyTree,
  "tt-tree": ttTree,
  "ttf-tree": ttfTree,
  btree,
  bplus,
  "binomial-heap": binomialHeap,
  "fibonacci-heap": fibonacciHeap,
  "radix-trie": radixTrie,
  tst: ternarySearchTree,
  fenwick,
  "interval-tree": intervalTree,
  "suffix-tree": suffixTree,
  cartesian,
  "kd-tree": kdTree,
};

export function getTreeAlgo(id: TreeAlgoId): TreeMeta {
  const item = TREE_META.find((m) => m.id === id);
  if (!item) throw new Error(`Unknown tree algorithm: ${id}`);
  return item;
}

export function runTreeAlgo(id: TreeAlgoId, input: TreeInput) {
  const runner = TREE_RUNNERS[id];
  if (!runner) throw new Error(`Tree algorithm not available: ${id}`);
  return runner(input);
}
